FROM python:3.6-alpine
WORKDIR /WorldOfGames 
COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt
RUN pip3 install selenium
COPY . /WorldOfGames
CMD python WorldOfGames/MainGame.py